# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180426_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='visualQuality',
        ),
        migrations.AlterField(
            model_name='parts',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[home.validators.validate_category]),
        ),
    ]
