# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_parts_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='images',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
