# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-01 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imagefile',
            new_name='imageFile',
        ),
        migrations.AddField(
            model_name='parts',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parts',
            name='images',
            field=models.FileField(null=True, upload_to='images/%Y/%m/%D/', verbose_name=''),
        ),
    ]
