# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180708_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='images',
            field=models.FileField(null=True, upload_to='images/%Y/%m/%D/', verbose_name=''),
        ),
    ]
