# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20180709_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of your product', max_length=30)),
                ('category', models.CharField(blank=True, max_length=120, null=True, validators=[home.validators.validate_category])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Manufacturer name', max_length=30)),
                ('modelName', models.CharField(blank=True, help_text='Model name', max_length=255)),
                ('manufacturingYear', models.CharField(blank=True, help_text='Manufacturing year', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Description about the product', max_length=3000)),
                ('usedDuration', models.CharField(blank=True, help_text='Number of years the product is used', max_length=30)),
                ('images', models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%D/', verbose_name='')),
                ('is_available', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parts Request',
                'verbose_name_plural': 'Parts Requests',
            },
        ),
    ]
