# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-09 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_partsrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partsrequest',
            name='images',
        ),
        migrations.RemoveField(
            model_name='partsrequest',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='partsrequest',
            name='updated',
        ),
    ]
