# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180709_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
