# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180710_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of your user', max_length=30)),
                ('email', models.CharField(blank=True, help_text='Email address', max_length=120, null=True)),
                ('subject', models.CharField(blank=True, help_text='Subject of contact', max_length=30)),
                ('message', models.CharField(blank=True, help_text='Description Of the problem', max_length=3000)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
