# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='city',
            field=models.CharField(blank=True, help_text='City where the product is', max_length=30),
        ),
        migrations.AddField(
            model_name='parts',
            name='country',
            field=models.CharField(blank=True, help_text='Country where product is', max_length=3000),
        ),
        migrations.AddField(
            model_name='parts',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Zip Code of where product is', max_length=30),
        ),
        migrations.AddField(
            model_name='partsrequest',
            name='city',
            field=models.CharField(blank=True, help_text='City where the product is', max_length=30),
        ),
        migrations.AddField(
            model_name='partsrequest',
            name='country',
            field=models.CharField(blank=True, help_text='Country where product is', max_length=3000),
        ),
        migrations.AddField(
            model_name='partsrequest',
            name='zipcode',
            field=models.CharField(blank=True, help_text='Zip Code of where product is', max_length=30),
        ),
    ]
