# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180712_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='city',
            field=models.CharField(blank=True, default='Paris', help_text='City where the product is', max_length=30),
        ),
        migrations.AlterField(
            model_name='parts',
            name='country',
            field=models.CharField(blank=True, default='France', help_text='Country where product is', max_length=3000),
        ),
        migrations.AlterField(
            model_name='parts',
            name='zipcode',
            field=models.CharField(blank=True, default='75001', help_text='Zip Code of where product is', max_length=30),
        ),
    ]
