# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-13 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('fullname', models.CharField(blank=True, help_text='Full name.', max_length=30)),
                ('address', models.CharField(blank=True, help_text='House number and street', max_length=255)),
                ('city', models.CharField(blank=True, help_text='Optional.', max_length=30)),
                ('postalcode', models.CharField(blank=True, help_text='Optional.', max_length=10)),
                ('country', models.CharField(blank=True, help_text='Optional.', max_length=30)),
                ('mobilenumber', models.IntegerField(blank=True, help_text='Optional.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
