# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notifications', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='part_id',
            field=models.PositiveIntegerField(),
        ),
    ]
