# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-01 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0002_auto_20180701_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_available',
            new_name='is_valid',
        ),
    ]
