# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0003_auto_20180701_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seller_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
