# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0004_notification_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('buyer_id', models.PositiveIntegerField()),
                ('seller_id', models.PositiveIntegerField()),
                ('part_id', models.PositiveIntegerField()),
                ('message', models.CharField(help_text='Messagr from seller', max_length=255)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Reply',
            },
        ),
    ]
