# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0006_notification_buyer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='part_name',
            field=models.CharField(blank=True, help_text='Name of your product', max_length=30),
        ),
    ]
