# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0008_reply_exchange_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='exchange_part_id',
            field=models.PositiveIntegerField(),
        ),
    ]
