# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notif', '0009_auto_20180710_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='message',
            field=models.CharField(help_text='Message from seller', max_length=255),
        ),
    ]
